/** Shared coin list for wallet assets */
export const WALLET_COINS = ['BTC', 'LTC', 'ETH', 'DOGE', 'USDT']

export const DEFAULT_FEES = {
  BTC: 0.000006,
  LTC: 0.00001,
  DOGE: 1,
  ETH: null,
  USDT: null,
}

export const TV_SYMBOLS = {
  BTC: 'BITSTAMP:BTCUSD',
  ETH: 'BITSTAMP:ETHUSD',
  LTC: 'BITSTAMP:LTCUSD',
  DOGE: 'BINANCE:DOGEUSDT',
  USDT: 'CRYPTOCAP:USDT',
  BNB: 'BINANCE:BNBUSDT',
  SOL: 'BINANCE:SOLUSDT',
  XRP: 'BINANCE:XRPUSDT',
  ADA: 'BINANCE:ADAUSDT',
  SHIB: 'BINANCE:SHIBUSDT',
}

export const TV_OVERVIEW_SYMBOLS = [
  ['BITSTAMP:BTCUSD|1D'],
  ['BITSTAMP:ETHUSD|1D'],
  ['BINANCE:USDTUSD|1D'],
  ['BINANCE:DOGEUSDT|1D'],
  ['BITSTAMP:LTCUSD|1D'],
  ['BINANCE:SOLUSDT|1D'],
  ['BINANCE:XRPUSDT|1D'],
  ['BINANCE:BNBUSDT|1D'],
  ['BINANCE:ADAUSDT|1D'],
  ['BINANCE:SHIBUSDT|1D'],
  ['BINANCE:AVAXUSDT|1D'],
  ['BINANCE:DOTUSDT|1D'],
  ['BINANCE:LINKUSDT|1D'],
  ['BINANCE:MATICUSDT|1D'],
  ['BINANCE:TRXUSDT|1D'],
]
